/*
 *  Copyright (C) 2023-2026 Team Xodi
 *  This file is part of Xodi - https://xodi.tv
 *
 *  SPDX-License-Identifier: GPL-2.0-or-later
 *  See LICENSES/README.md for more information.
 */

#pragma once

#include <map>
#include <string>

#include "utils/XBMCTinyXML.h"

// CMarkupSTL compatibility wrapper around Kodi's TinyXML wrapper - Generated by AI!.
class CMarkupSTL
{
public:
  CMarkupSTL();
  CMarkupSTL(const char* szDoc);
  CMarkupSTL(const CMarkupSTL& markup);
  ~CMarkupSTL() {}

  void operator=(const CMarkupSTL& markup);

  bool SetDoc(const char* szDoc);
  bool Load(const char* szFileName);
  bool Save(const char* szFileName);
  bool IsWellFormed();

  std::string GetDoc() const;
  std::string GetError() const;

  bool FindElem(const char* szName = NULL);
  bool FindChildElem(const char* szName = NULL);
  bool IntoElem();
  bool OutOfElem();

  void ResetPos();
  void ResetMainPos();
  void ResetChildPos();

  std::string GetTagName() const;
  std::string GetChildTagName() const;
  std::string GetData() const;
  std::string GetChildData() const;
  std::string GetAttrib(const char* szAttrib) const;
  std::string GetChildAttrib(const char* szAttrib) const;
  std::string GetAttribName(int n) const;
  std::string GetChildSubDoc() const;

  bool SetData(const char* szData, int nCDATA = 0);
  bool SetChildData(const char* szData, int nCDATA = 0);
  bool SetAttrib(const char* szAttrib, const char* szValue);
  bool SetAttrib(const char* szAttrib, int nValue);
  bool SetChildAttrib(const char* szAttrib, const char* szValue);
  bool SetChildAttrib(const char* szAttrib, int nValue);

  // Markup 6.3 aliases. AddAttrib/SetAttrib have the same effect.
  bool AddAttrib(const char* szAttrib, const char* szValue) { return SetAttrib(szAttrib, szValue); }
  bool AddAttrib(const char* szAttrib, int nValue) { return SetAttrib(szAttrib, nValue); }
  bool AddChildAttrib(const char* szAttrib, const char* szValue) { return SetChildAttrib(szAttrib, szValue); }
  bool AddChildAttrib(const char* szAttrib, int nValue) { return SetChildAttrib(szAttrib, nValue); }

  bool AddElem(const char* szName, const char* szData = NULL);
  bool InsertElem(const char* szName, const char* szData = NULL);
  bool AddChildElem(const char* szName, const char* szData = NULL);
  bool InsertChildElem(const char* szName, const char* szData = NULL);

  bool AddChildSubDoc(const char* szSubDoc);
  bool InsertChildSubDoc(const char* szSubDoc);

  bool RemoveChildElem();

  bool SavePos(const char* szPosName = "");
  bool RestorePos(const char* szPosName = "");

  // TinyXML does not maintain source byte offsets. This compatibility method
  // computes offsets in the current serialized document. It is intended only
  // for legacy callers; DOM operations should not depend on these offsets.
  bool GetOffsets(int& nStart, int& nEnd) const;

private:
  struct SavedPos
  {
    TiXmlElement* parent;
    TiXmlElement* elem;
    TiXmlElement* child;
  };

  CXBMCTinyXML m_doc;
  TiXmlElement* m_parent;
  TiXmlElement* m_elem;
  TiXmlElement* m_child;
  std::map<std::string, SavedPos> m_savedPos;
  std::string m_error;

  TiXmlElement* FirstElement(TiXmlNode* parent);
  TiXmlElement* NextElement(TiXmlElement* current) const;
  TiXmlElement* FindNext(TiXmlNode* parent, TiXmlElement* current, const char* name);

  static std::string ElementText(const TiXmlElement* elem);
  static std::string SerializeNode(const TiXmlNode* node);

  bool SetElementData(TiXmlElement* elem, const char* data, int cdata);
  bool SetElementAttrib(TiXmlElement* elem, const char* name, const char* value);
  bool SetElementAttrib(TiXmlElement* elem, const char* name, int value);

  bool AddElement(const char* name, const char* data, bool insert, bool child);
  bool AddSubDoc(const char* subDoc, bool insert, bool child);

  void CopyFrom(const CMarkupSTL& markup);
};
